# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4acd6710a59c20831cb70223980813afc851abe8d0d8b0caf6e92768d9af74d3adf38d63b9751f2ecc6e47e50748be90c8bda6df9f37bec051d5536ec829857a

test:
  secret_key_base: f13b9c67977ad3d32cc5321c28c0367a5c31a9ee1dd082703f05e5d9ce3b9d42ac5c3798f22b3590de32738b64df3dd2e35c256bcf0b4a5345bd1c2fe75659a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
